# style
set -g status-position bottom
set -g status-style "bg=default,fg=white"
setw -g window-status-format "#[fg=colour242,bg=default]#W"            
setw -g window-status-current-format "#[bold]#[fg=white,bg=default]#W"
set -g status-justify absolute-centre
set -g status-interval 1
set -g renumber-windows on
set -g status-left ""
set -g status-right ""

# bind
set -g prefix M-a
bind h split-pane -h -c "#{pane_current_path}"
bind v split-pane -v -c "#{pane_current_path}"

bind -n M-Enter new-window -c "#{pane_current_path}"

bind -n M-h if-shell "[ #{pane_at_left} -eq 1 ]" "previous-window" "select-pane -L"
bind -n M-l if-shell "[ #{pane_at_right} -eq 1 ]" "next-window" "select-pane -R"

bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-H resize-pane -L 2
bind -n M-L resize-pane -R 2
bind -n M-K resize-pane -U 1
bind -n M-J resize-pane -D 1

bind -n M-q kill-pane
bind -n M-i copy-mode

bind -T copy-mode-vi v send-keys -X begin-selection

set -g mouse on
set -g default-terminal "foot"
set -ga terminal-overrides ",*:Tc"
