return {
	--  mode              key          cmd                            --
	--------------------------------------------------------------------
	{ { "n", "v" },       "<C-a>",     "ggVG"                          },
	{   "n",              "<leader>f", function() fzy_finder(true) end },
	{   "n",              "<C-j>",     "<C-w>w"                        },
	{   "n",              "<C-k>",     "<C-w>W"                        },
	{   "n",              "<C-h>",     "<C-w><"                        },
	{   "n",              "<C-l>",     "<C-w>>"                        },
	{   "n",              "<C-f>",     "<C-w>x"                        },
	{   "n",              "<A-k>",     ":m .-2<CR>=="                  },
	{   "n",              "<A-j>",     ":m .+1<CR>=="                  },
	{   "v",              "<A-k>",     ":silent m '<-2<CR>gv=gv"       },
	{   "v",              "<A-j>",     ":silent m '>+1<CR>gv=gv"       },
	{   "n",			  "<leader>j", ":%s//g<Left><Left>"            },
	{   "v",			  "<leader>j", ":s//g<Left><Left>"             },
	{ { "n", "v" },		  "te",        ":tabedit "                     },
	{ { "n", "v" },		  "<S-l>",     ":tabnext<CR>"                  },
	{ { "n", "v" },       "<",         "<gv"                           },
	{ { "n", "v" },       ">",         ">gv"                           },
	{ { "n", "v" },       "<S-h>",     ":tabprev<CR>"                  },
	{ { "n", "v" },       "E",         ":e "                           },
	{ { "n", "v" },       "sv",        ":vsplit "                      },
	{ { "n", "v" },       "ss",        ":split "                       },
	{ { "n", "v" },       "<CR>",      ":!make -B<CR>"                 },
	{   "n",              "<leader>k", ":tabedit <cfile><CR>"          },
    { { "n", "v" },       "<C-e>",     ":source ~/.config/nvim/init.lua <CR>" },
	{   "n",              "gd",        ":tab split | lua vim.lsp.buf.definition()<CR>" },
	{   "n",              "<leader>g", function() gdb() end           },
	{   "n",              "<A-/>",     require("Comment.api").toggle.linewise.current },
	{   "v",              "<A-/>",     function() vim.api.nvim_feedkeys("gc", "x", false ) end },
}
