return {
	--  mode              key          cmd                            --
	--------------------------------------------------------------------
	{   "n",              "ff",        function() fzy_finder(true) end },
	{   "n",			  "fd",        ":%s//g<Left><Left>"            },
	{   "v",			  "fd",        ":s//g<Left><Left>"             },
	{   "t",              "<Esc>",     [[<C-\><C-n>]]                  },
	{   "n",              "<C-f>",     ":nohlsearch<CR>"               },
	{   "n",              "<C-k>",     ":m .-2<CR>=="                  },
	{   "n",              "<C-j>",     ":m .+1<CR>=="                  },
	{   "v",              "<C-k>",     ":silent m '<-2<CR>gv=gv"       },
	{   "v",              "<C-j>",     ":silent m '>+1<CR>gv=gv"       },
	{   "n",              "<C-o>",     ":tabedit <cfile><CR>"          },
	{ { "n", "v" },       "<C-e>",     ":so $MYVIMRC <CR>"             },
	{ { "n", "v" },       "<C-a>",     "ggVG"                          },
	{   "n",              "<leader>n", gs.next_hunk                    },
	{   "n",              "<leader>p", gs.prev_hunk                    },
	{   "n",              "<leader>s", gs.stage_hunk                   },
	{   "n",              "<leader>u", gs.undo_stage_hunk              },
	{   "n",              "<leader>r", gs.reset_hunk                   },
	{   "n",              "<leader>f", gs.preview_hunk     	           },
	{   "n",              "<leader>i", gs.toggle_current_line_blame    },
	{   "n",              "<leader>i", ":!git commit -m "              },
	{ { "n", "v" },		  "<S-l>",     ":tabnext<CR>"                  },
	{ { "n", "v" },       "<S-h>",     ":tabprev<CR>"                  },
	{ { "n", "v" },       "<",         "<gv"                           },
	{ { "n", "v" },       ">",         ">gv"                           },
	{ { "n", "v" },       "<S-h>",     ":tabprev<CR>"                  },
	{ { "n", "v" },       "E",         ":e "                           },
	{ { "n", "v" },       "sv",        ":vsplit "                      },
	{ { "n", "v" },       "ss",        ":split "                       },
	{ { "n", "v" },       "<CR>",      ":!make -B<CR>"                 },
	{   "n",              "<leader>k", ":tabedit <cfile><CR>"          },
    { { "n", "v" },       "<C-e>",     ":source ~/.config/nvim/init.lua <CR>" },
	{   "n",              "gd",        ":tab split | lua vim.lsp.buf.definition()<CR>" },
	{   "n",              "<leader>g", function() gdb() end           },
	{   "n",              "<A-/>",     require("Comment.api").toggle.linewise.current },
	{   "n",              "gd",        ":tab split | lua vim.lsp.buf.definition()<CR>" },
}
