-- Options
return {
	clipboard          = "unnamedplus",
	shiftwidth         = 2,
	smartindent        = true,
	number             = true,
	relativenumber     = true,
	tabstop            = 4,
	swapfile           = false,
	hlsearch           = true,
	startofline        = false,
	mouse              = "a",
	wrap               = false,
	scrolloff          = 1,
	ignorecase         = true,
	smartcase          = true,
	showcmd            = true,
	showmatch          = true,
	history            = 1000,
	wildmenu           = true,
	undofile           = true,
	undodir            = vim.fn.expand("~/.local/state/nvim/undo"),
	cursorline         = false,
	wildmode           = "longest:full,full",
	wildignore         = "*.docx,*.we*,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.svg,*.flv,*.img,*.xlsx",
	clipboard          = "unnamedplus",
	termguicolors      = true,
	backup             = false,
	writebackup        = false,
	cmdheight          = 0,
	laststatus         = 2,
	statusline         = "%#Normal#%{mode() ==# 'n' ? 'NORMAL' : mode() ==# 'i' ? 'INSERT' : mode() ==# 'v' ? 'VISUAL' : 'OTHER'} %{&modified?'+':''} %= %{luaeval('_G.lsp_diagnostics()')} %f",
}
